### ISSUE TITLE
Data does not get saved when doctor puts first time in diagnosis, medication, advice, test

### ISSUE THREAD

**Issue by prithi69** [Intelehealth/intelehealth-openmrs-module#44]
after adding the medications, diagnosis, advice, test:
![untitled-1](https://user-images.githubusercontent.com/28602886/29486452-88f6f7f8-8503-11e7-9055-f66e19734e59.png)

Refreshing the page, medications, advice, test got vanished.
![untitled-2](https://user-images.githubusercontent.com/28602886/29486465-ba728fb8-8503-11e7-86c1-f9d38f7bb298.png)

**Comment by prithi69** [comment]
ITS a Rest API ISSUE..

**Comment by prithi69** [comment]
400 bad request is coming on angular.js

**Comment by nehagoel2** [comment]
So I was able to replicate this issue, I am not sure of the cause, it does not appear to be occuring on any other page of the ref app, so it may have to do with optimizing angular code.

**Comment by amalafrozalam** [comment]
Break through! 
So issue 23 is being CAUSED by this issue. When the code looks to see if these sections are filled in, it doesn't find anything. I _think_ this is what is causing issue 23.

**Comment by amalafrozalam** [comment]
So data _is_ saved to the database, but it seems like it's not retrieved properly.

**Comment by amalafrozalam** [comment]
Diagnosis still does not work. But I cannot replicate the issue. I have tried with 5 different patients, but I am able to retrieve the data I posted. Screenshots are provided below:

![screen shot 2017-12-07 at 4 29 47 pm](https://user-images.githubusercontent.com/3815106/33739758-46004c6e-db6c-11e7-9a9c-1a185acaf53f.png)
This is what it looks like before I do anything. 


![screen shot 2017-12-07 at 4 31 43 pm](https://user-images.githubusercontent.com/3815106/33739757-45f76360-db6c-11e7-9acc-cb1c280b729d.png)
This is me after putting in some information.

![screen shot 2017-12-07 at 4 31 54 pm](https://user-images.githubusercontent.com/3815106/33739756-45eaae5e-db6c-11e7-91ab-a4c06af805da.png)
This is me after refreshing the page to see if I can see what I wrote. 

![screen shot 2017-12-07 at 4 33 52 pm](https://user-images.githubusercontent.com/3815106/33739795-6bebe6b8-db6c-11e7-989a-23beaee52d96.png)
This is me after completely logging out and reviewing the page. Note, I also checked if issue #23 is being replicated, it is not. 

![screen shot 2017-12-07 at 4 37 46 pm](https://user-images.githubusercontent.com/3815106/33739964-f817f8ac-db6c-11e7-85ec-e7093c592ecf.png)
And this is me after completely **restarting** the server.

I have no idea how/if this issue is being caused. Perhaps the REST API on the other machines was out of date, broken, or something else.

**Comment by amalafrozalam** [comment]
@nehagoel2 and @prithi69 please report the steps you take to replicate this issue. Because I have no idea what is happening.

**Comment by amalafrozalam** [comment]
This will be posted on OpenMRS talk.

**Comment by prithi69** [comment]
Data have been posted now with one encounter, tested in cloud and local,
