### ISSUE TITLE
Data needs to be posted into the database in a way that is indexable

### ISSUE THREAD

**Issue by hardikk08** [Intelehealth/intelehealth-openmrs-module#76]

**Comment by nehav39** [comment]
Remove HTML tags and format obs on OpenMRS itself

Need: Database elements in the obs table need to be searchable currently not possible because of the way the OpenMRS database is indexed - it skips over any cell which begins with a special character
What is this list of special characters? <br>, “<”, “>”?
Solution A: Once a month, or as required, make a copy of the existing database, a Python script scrubs the database of all html tags --- until middleware is built
Solution B: Using markdown parsers - changes need to be made on both the Android and on OpenMRS --- until middleware is built 
[#, .] are the markdown parsers
Solution C: Multiple posts for each data point (Too bandwidth intensive)
Solution D: Middleware to handle the multiple posts
Solution E: Change the OpenMRS indexing
Solution F: Change the obs type to complex or varchar
Solution G: Remove any HTML tags/markdown parsers in the beginning, but keep in the body
Which of the following works?
<h1>Complaint</h1><br><p>something</p><br>
Complaint<br><p>something</p><br>
#Complaint. Something.
Complaint#. #Something.
Complaint. Something.
Select count(obs_id) from obs where value_text= “Bleeding”;
Can you change the obs type to value_complex, value_varchar?

**Comment by nehav39** [comment]
Abdominal pain:

- Since 2 weeks
- nature something

How does indexing work???


` <b>Abdominal pain <br><ul> Since 2 weeks</ul>......`
`#Abdominal Pain. Since 2 weeks. .....`
`Abdominal Pain. Since 2 weeks. #Back Pain`

**Comment by nehav39** [comment]
moved to new repo
